(deftheme one-dark-beautify
  "Created 2018-06-11.")

(custom-theme-set-variables
 'one-dark-beautify
 )

(custom-theme-set-faces
 'one-dark-beautify
 '(success ((t (:foreground "#98C379"))))
 '(warning ((t (:foreground "#E5C07B"))))
 '(error ((t (:foreground "#E06C75" :weight bold))))
 '(link ((t (:foreground "#61AFEF" :underline t :weight bold))))
 '(link-visited ((t (:foreground "#61AFEF" :underline t :weight normal))))
 '(cursor ((t (:background "#528BFF"))))
 '(fringe ((t (:background "#282C34"))))
 '(region ((t (:background "#3E4451"))))
 '(highlight ((t (:background "#3E4451"))))
 '(hl-line ((t (:background "#2C323C"))))
 '(vertical-border ((t (:background "#181A1F" :foreground "#181A1F"))))
 '(secondary-selection ((t (:background "#121417"))))
 '(query-replace ((t (:inherit (isearch)))))
 '(minibuffer-prompt ((t (:foreground "#9DA5B4"))))
 '(font-lock-builtin-face ((t (:foreground "#56B6C2"))))
 '(font-lock-comment-face ((t (:foreground "#5C6370" :slant italic))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:foreground "#61AFEF"))))
 '(font-lock-keyword-face ((t (:foreground "#C678DD" :slant italic :weight normal))))
 '(font-lock-preprocessor-face ((t (:foreground "#828997"))))
 '(font-lock-string-face ((t (:foreground "#98C379"))))
 '(font-lock-type-face ((t (:foreground "#E5C07B"))))
 '(font-lock-constant-face ((t (:foreground "#56B6C2"))))
 '(font-lock-variable-name-face ((t (:foreground "#E06C75"))))
 '(font-lock-warning-face ((t (:foreground "#5C6370" :bold t))))
 '(mode-line ((t (:background "#21252B" :foreground "#9DA5B4" :box (:color "#181A1F" :line-width 1)))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-inactive ((t (:background "#181A1F" :foreground "#3E4451" :box (:color "#181A1F" :line-width 1)))))
 '(ido-first-match ((t (:foreground "#C678DD" :weight bold))))
 '(ido-only-match ((t (:foreground "#E06C75" :weight bold))))
 '(ido-subdir ((t (:foreground "#61AFEF"))))
 '(ido-virtual ((t (:foreground "#5C6370"))))
 '(company-tooltip ((t (:foreground "#ABB2BF" :background "#121417"))))
 '(company-tooltip-annotation ((t (:foreground "#828997" :background "#121417"))))
 '(company-tooltip-selection ((t (:foreground "#ABB2BF" :background "#3E4451"))))
 '(company-tooltip-mouse ((t (:background "#3E4451"))))
 '(company-tooltip-common ((t (:foreground "#E5C07B" :background "#121417"))))
 '(company-tooltip-common-selection ((t (:foreground "#E5C07B" :background "#3E4451"))))
 '(company-preview ((t (:background "#282C34"))))
 '(company-preview-common ((t (:foreground "#E5C07B" :background "#282C34"))))
 '(company-scrollbar-fg ((t (:background "#ABB2BF"))))
 '(company-scrollbar-bg ((t (:background "#121417"))))
 '(compilation-line-number ((t (:foreground "#828997"))))
 '(compilation-column-number ((t (:foreground "#828997"))))
 '(isearch ((t (:foreground "#282C34" :background "#C678DD"))))
 '(isearch-fail ((t (:foreground "#BE5046" :background nil))))
 '(lazy-highlight ((t (:foreground "#C678DD" :background "#121417" :underline "#C678DD"))))
 '(dired-directory ((t (:inherit (font-lock-keyword-face)))))
 '(dired-flagged ((t (:inherit (diff-hl-delete)))))
 '(dired-symlink ((t (:foreground "#FD5FF1"))))
 '(helm-header ((t (:foreground "#828997" :background "#282C34" :underline nil :box (:line-width 6 :color "#282C34")))))
 '(helm-source-header ((t (:foreground "#E5C07B" :background "#282C34" :underline nil :weight bold :box (:line-width 6 :color "#282C34")))))
 '(helm-selection ((t (:background "#3E4451"))))
 '(helm-selection-line ((t (:background "#3E4451"))))
 '(helm-visible-mark ((t (:foreground "#282C34" :foreground "#E5C07B"))))
 '(helm-candidate-number ((t (:foreground "#98C379" :background "#121417"))))
 '(helm-separator ((t (:background "#282C34" :foreground "#E06C75"))))
 '(helm-match ((t (:foreground "#E5C07B"))))
 '(info-menu-star ((t (:foreground "#E06C75"))))
 '(ivy-confirm-face ((t (:inherit minibuffer-prompt :foreground "#98C379"))))
 '(ivy-current-match ((t (:background "#3E4451" :weight normal))))
 '(ivy-highlight-face ((t (:inherit font-lock-builtin-face))))
 '(ivy-match-required-face ((t (:inherit minibuffer-prompt :foreground "#E06C75"))))
 '(ivy-minibuffer-match-face-1 ((t (:background "#2C323C"))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit ivy-minibuffer-match-face-1 :background "#21252B" :foreground "#C678DD" :weight semi-bold))))
 '(ivy-minibuffer-match-face-3 ((t (:inherit ivy-minibuffer-match-face-2 :background "#21252B" :foreground "#98C379" :weight semi-bold))))
 '(ivy-minibuffer-match-face-4 ((t (:inherit ivy-minibuffer-match-face-2 :background "#21252B" :foreground "#E5C07B" :weight semi-bold))))
 '(ivy-minibuffer-match-highlight ((t (:foreground "#61AFEF"))))
 '(ivy-modified-buffer ((t (:inherit default :foreground "#D19A66"))))
 '(ivy-virtual ((t (:inherit font-lock-builtin-face :slant italic))))
 '(counsel-key-binding ((t (:foreground "#E5C07B" :weight bold))))
 '(git-commit-comment-action ((t (:foreground "#98C379" :weight bold))))
 '(git-commit-comment-branch-local ((t (:foreground "#61AFEF" :weight bold))))
 '(git-commit-comment-heading ((t (:foreground "#E5C07B" :weight bold))))
 '(magit-section-highlight ((t (:background "#2C323C"))))
 '(magit-section-heading ((t (:foreground "#E5C07B" :weight bold))))
 '(magit-section-heading-selection ((t (:foreground "#ABB2BF" :weight bold))))
 '(magit-diff-file-heading ((t (:weight bold))))
 '(magit-diff-file-heading-highlight ((t (:background "#3E4451" :weight bold))))
 '(magit-diff-file-heading-selection ((t (:foreground "#E5C07B" :background "#2C323C" :weight bold))))
 '(magit-diff-hunk-heading ((t (:foreground "#828997" :background "#3E4451"))))
 '(magit-diff-hunk-heading-highlight ((t (:foreground "#ABB2BF" :background "#5C6370"))))
 '(magit-diff-hunk-heading-selection ((t (:foreground "#C678DD" :background "#5C6370"))))
 '(magit-diff-context ((t (:foreground "#ABB2BF"))))
 '(magit-diff-context-highlight ((t (:background "#121417" :foreground "#ABB2BF"))))
 '(magit-diffstat-added ((t (:foreground "#98C379"))))
 '(magit-diffstat-removed ((t (:foreground "#E06C75"))))
 '(magit-process-ok ((t (:foreground "#98C379"))))
 '(magit-process-ng ((t (:foreground "#E06C75"))))
 '(magit-log-author ((t (:foreground "#E5C07B"))))
 '(magit-log-date ((t (:foreground "#828997"))))
 '(magit-log-graph ((t (:foreground "#9DA5B4"))))
 '(magit-sequence-pick ((t (:foreground "#E5C07B"))))
 '(magit-sequence-stop ((t (:foreground "#98C379"))))
 '(magit-sequence-part ((t (:foreground "#D19A66"))))
 '(magit-sequence-head ((t (:foreground "#61AFEF"))))
 '(magit-sequence-drop ((t (:foreground "#E06C75"))))
 '(magit-sequence-done ((t (:foreground "#828997"))))
 '(magit-sequence-onto ((t (:foreground "#828997"))))
 '(magit-bisect-good ((t (:foreground "#98C379"))))
 '(magit-bisect-skip ((t (:foreground "#D19A66"))))
 '(magit-bisect-bad ((t (:foreground "#E06C75"))))
 '(magit-blame-heading ((t (:background "#121417" :foreground "#828997"))))
 '(magit-blame-hash ((t (:background "#121417" :foreground "#C678DD"))))
 '(magit-blame-name ((t (:background "#121417" :foreground "#E5C07B"))))
 '(magit-blame-date ((t (:background "#121417" :foreground "#5C6370"))))
 '(magit-blame-summary ((t (:background "#121417" :foreground "#828997"))))
 '(magit-dimmed ((t (:foreground "#828997"))))
 '(magit-hash ((t (:foreground "#C678DD"))))
 '(magit-tag ((t (:foreground "#D19A66" :weight bold))))
 '(magit-branch-remote ((t (:foreground "#98C379" :weight bold))))
 '(magit-branch-local ((t (:foreground "#61AFEF" :weight bold))))
 '(magit-branch-current ((t (:foreground "#61AFEF" :weight bold :box t))))
 '(magit-head ((t (:foreground "#61AFEF" :weight bold))))
 '(magit-refname ((t (:background "#282C34" :foreground "#ABB2BF" :weight bold))))
 '(magit-refname-stash ((t (:background "#282C34" :foreground "#ABB2BF" :weight bold))))
 '(magit-refname-wip ((t (:background "#282C34" :foreground "#ABB2BF" :weight bold))))
 '(magit-signature-good ((t (:foreground "#98C379"))))
 '(magit-signature-bad ((t (:foreground "#E06C75"))))
 '(magit-signature-untrusted ((t (:foreground "#D19A66"))))
 '(magit-cherry-unmatched ((t (:foreground "#56B6C2"))))
 '(magit-cherry-equivalent ((t (:foreground "#C678DD"))))
 '(magit-reflog-commit ((t (:foreground "#98C379"))))
 '(magit-reflog-amend ((t (:foreground "#C678DD"))))
 '(magit-reflog-merge ((t (:foreground "#98C379"))))
 '(magit-reflog-checkout ((t (:foreground "#61AFEF"))))
 '(magit-reflog-reset ((t (:foreground "#E06C75"))))
 '(magit-reflog-rebase ((t (:foreground "#C678DD"))))
 '(magit-reflog-cherry-pick ((t (:foreground "#98C379"))))
 '(magit-reflog-remote ((t (:foreground "#56B6C2"))))
 '(magit-reflog-other ((t (:foreground "#56B6C2"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "#ABB2BF"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "#C678DD"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "#61AFEF"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "#56B6C2"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "#98C379"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "#D19A66"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "#E5C07B"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "#E06C75"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#BE5046"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "#21252B"))))
 '(sp-show-pair-mismatch-face ((t (:foreground "#E06C75" :background "#3E4451" :weight bold))))
 '(sp-show-pair-match-face ((t (:background "#3E4451" :weight bold))))
 '(linum ((t (:foreground "#4B5363" :background "#282C34"))))
 '(line-number ((t (:foreground "#4B5363" :background "#282C34"))))
 '(line-number-current-line ((t (:foreground "#ABB2BF" :background "#282C34"))))
 '(org-date ((t (:foreground "#56B6C2"))))
 '(org-footnote ((t (:foreground "#56B6C2"))))
 '(org-sexp-date ((t (:foreground "#56B6C2"))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#E06C75"))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#D19A66"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#56B6C2"))))
 '(default ((t (:foreground "#ABB2BF" :background "#282C34"))))
 '(org-agenda-structure ((t (:inherit default :font "Lucida Grande" :height 1.3 :underline nil))))
 '(org-level-8 ((t (:inherit default :foreground "#ABB2BF"))))
 '(org-level-7 ((t (:inherit default :foreground "#ABB2BF"))))
 '(org-level-6 ((t (:inherit default :foreground "#ABB2BF"))))
 '(org-level-5 ((t (:inherit default :foreground "#ABB2BF"))))
 '(org-level-4 ((t (:inherit default :foreground "#ABB2BF"))))
 '(org-level-3 ((t (:inherit default :foreground "#ABB2BF" :height 1.2 :box nil))))
 '(org-level-2 ((t (:inherit default :foreground "#ABB2BF" :font "Lucida Grande" :height 1.25 :box nil))))
 '(org-level-1 ((t (:inherit default :foreground "#ABB2BF" :font "Lucida Grande" :height 1.4 :box nil))))
 '(org-document-title ((t (:inherit org-level-1 :height 1.5 :underline nil :box nil))))
 '(org-block ((t (:foreground "#ABB2BF" :background "#282C34" :box nil))))
 '(org-checkbox ((t (:foreground "#000000" :background "#93a1a1" :box (:line-width -3 :color "#93a1a1" :style "released-button")))))
 '(org-headline-done ((t (:strike-through t))))
 '(org-done ((t (:strike-through t))))
 '(org-block-begin-line ((t (:inherit (org-meta-line default) :background "#35373E" :foreground "#ABB2BF"))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-verbatim ((t (:inherit (shadow fixed-pitch-serif))))))

(provide-theme 'one-dark-beautify)
