%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%  `(file-name-sans-extension (file-name-nondirectory (buffer-file-name)))` A package for $1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{`(file-name-sans-extension (file-name-nondirectory (buffer-file-name))))`}[`(format-time-string "%D" (current-time))` A class for $1]
$2
\endinput
